# Generated by Django 4.1.7 on 2023-04-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='one',
            fields=[
                ('Onee', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tw', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gg', models.CharField(max_length=100)),
                ('Onee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.one')),
            ],
        ),
    ]
